const animations = {
    pikachu: require('../assets/animations/pikachu.json'),
    toaster: require('../assets/animations/toaster.json'),
    zenWork: require('../assets/animations/zenWork.json'),
    animeGirl: require('../assets/animations/animeGirl.json'),
    animeGuy: require('../assets/animations/animeGuy.json'), 
    catBox: require('../assets/animations/catBox.json'),
    catCool: require('../assets/animations/catCool.json'), 
    catSleep: require('../assets/animations/catSleep.json'), 
    catWitch: require('../assets/animations/catWitch.json'), 
    dogFloat: require('../assets/animations/dogFloat.json'), 
    dogWalk: require('../assets/animations/dogWalk.json'), 
    dogWalk2: require('../assets/animations/dogWalk2.json'), 
    eyeBlob: require('../assets/animations/eyeBlob.json'), 
    ghibliGirl: require('../assets/animations/ghibliGirl.json'), 
    girlCatEars: require('../assets/animations/girlCatEars.json'),
    gojoCat: require('../assets/animations/gojoCat.json'),
    meditationCoffee: require('../assets/animations/meditationCoffee.json'),
    meditationCow: require('../assets/animations/meditationCow.json'), 
    meditationGirl: require('../assets/animations/meditationGirl.json'), 
    meditationGuy: require('../assets/animations/meditationGuy.json'), 
    meditationMan2: require('../assets/animations/meditationMan2.json'), 
    meditationSloth: require('../assets/animations/meditationSloth.json'), 
    meditationTurtle: require('../assets/animations/meditationTurtle.json'),
    noFace: require('../assets/animations/noFace.json'), 
    nyanCat: require('../assets/animations/nyanCat.json'), 
    panda: require('../assets/animations/panda.json'), 
    ramen: require('../assets/animations/ramen.json'),
    robot: require('../assets/animations/robot.json'), 
    robotGamer: require('../assets/animations/robotGamer.json'), 
    spaceInvader: require('../assets/animations/spaceInvader.json'), 
    spaceJam: require('../assets/animations/spaceJam.json'), 
    spaceWork: require('../assets/animations/spaceWork.json'), 
    studying: require('../assets/animations/studying.json'),
};

export default animations;